In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as  plt
import seaborn as sns
import sqlite3

In [25]:
#1 importing database / data

In [26]:

conn = sqlite3.connect('customer_churn.db')

sql_query = """
    SELECT name
    FROM sqlite_master
    WHERE type = 'table'
"""

tables = pd.read_sql(sql_query, conn)

# create dataframe for each table

for table_name in tables['name']:
    df = pd.read_sql(f'SELECT * FROM {table_name}',conn)
    globals()[f'df_{table_name}'] = df
    print(f"Created dataframe: df_{table_name}")

conn.close()

Created dataframe: df_db_customer
Created dataframe: df_db_subscription
Created dataframe: df_db_support

In [27]:
# print table names and column names
conn = sqlite3.connect("customer_churn.db")

for table_name in tables['name']:
    print(f"\nTable Name: {table_name}")
    columns_query = f"PRAGMA table_info({table_name});"
    columns = pd.read_sql(columns_query, conn)
    print("Columns:")
    print(columns['name'].tolist())

conn.close()

Table Name: db_customer
Columns:
['customerid', 'name', 'country', 'state', 'gender', 'dob', 'interests', 'pincode']

Table Name: db_subscription
Columns:
['customerid', 'subscription_start_date', 'subscription_type', 'renewal_date', 'plan_type', 'contract_type', 'cancellation_date', 'cancellation_reason', 'monthly_charges', 'cltv', 'churn_score']

Table Name: db_support
Columns:
['customerid', 'complaint_date', 'escalations', 'csat_score', 'col_1', 'comment']

In [28]:
# Data cleaning

In [29]:
df_db_customer.head()

,customerid,name,country,state,gender,dob,interests,pincode
0,0002-ORFBO,keshav,India,Maharashtra,Male,1982-04-12 00:00:00,travel,None
1,0003-MKNFE,raghav,India,Karnataka,Male,1995-11-23 00:00:00,None,None
2,0004-TLHLJ,lalita,India,Delhi,Female,1978-02-15 00:00:00,movie,None
3,0011-IGKFF,mohan,India,Nagaland,Male,2001-08-30 00:00:00,None,None
4,0013-EXCHZ,mira,India,Delhi,Female,1990-05-05 00:00:00,drama,None

In [30]:
df_db_customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerid  21 non-null     object
 1   name        21 non-null     object
 2   country     18 non-null     object
 3   state       21 non-null     object
 4   gender      21 non-null     object
 5   dob         21 non-null     object
 6   interests   4 non-null      object
 7   pincode     0 non-null      object
dtypes: object(8)
memory usage: 1.4+ KB

In [31]:
df_db_customer.shape

(21, 8)

In [32]:
df_db_customer.rename(columns = {'name':'customer_name'},inplace=True)
df_db_customer

,customerid,customer_name,country,state,gender,dob,interests,pincode
0,0002-ORFBO,keshav,India,Maharashtra,Male,1982-04-12 00:00:00,travel,None
1,0003-MKNFE,raghav,India,Karnataka,Male,1995-11-23 00:00:00,None,None
2,0004-TLHLJ,lalita,India,Delhi,Female,1978-02-15 00:00:00,movie,None
3,0011-IGKFF,mohan,India,Nagaland,Male,2001-08-30 00:00:00,None,None
4,0013-EXCHZ,mira,India,Delhi,Female,1990-05-05 00:00:00,drama,None
5,0013-MHZWF,durga,None,Delhi,Women,1988-12-10 00:00:00,None,None
6,0013-SMEOE,mina,India,Meghalaya,Female,1976-09-21 00:00:00,None,None
7,0014-BMAQU,madan,India,Rajasthan,Male,1999-03-14 00:00:00,None,None
8,0015-UOCOJ,maya,None,Kathmandu,Women,1985-07-07 00:00:00,None,None
9,0016-QLJIS,arjun,Nepal,Kathmandu,Male,1993-10-29 00:00:00,None,None
10,0017-DINOC,shiva,India,Maharashtra,Men,1997-01-22 00:00:00,None,None
11,0017-IUDMW,rangadevi,India,Karnataka,Female,1981-06-18 00:00:00,None,None
12,0018-NYROU,chitra,None,Telangana,Female,2004-12-01 00:00:00,None,None
13,0019-EFAEP,raju,India,Meghalaya,Female,1992-04-25 00:00:00,None,None
14,0019-GFNTW,Madhav,India,Uttar Pradesh,Men,1979-11-11 00:00:00,None,None
15,0020-INWCK,parvati,India,Delhi,Female,1986-02-28 00:00:00,job,None
16,0020-JDNXP,rikim,India,Meghalaya,Female,1994-08-19 00:00:00,None,None
17,0021-IKXGC,vishakha,India,Rajasthan,Female,2000-09-02 00:00:00,None,None
18,0022-TCJCI,raghvendra,India,Telangana,Male,1983-12-30 00:00:00,None,None
19,0023-HGHWL,rishabh,India,Uttar Pradesh,Men,1991-05-14 00:00:00,None,None
20,0023-UYUPN,sudevi,India,Maharashtra,Women,1977-10-06 00:00:00,None,None

In [33]:
df_db_customer.drop(columns=['interests','pincode'],inplace=True)
df_db_customer

,customerid,customer_name,country,state,gender,dob
0,0002-ORFBO,keshav,India,Maharashtra,Male,1982-04-12 00:00:00
1,0003-MKNFE,raghav,India,Karnataka,Male,1995-11-23 00:00:00
2,0004-TLHLJ,lalita,India,Delhi,Female,1978-02-15 00:00:00
3,0011-IGKFF,mohan,India,Nagaland,Male,2001-08-30 00:00:00
4,0013-EXCHZ,mira,India,Delhi,Female,1990-05-05 00:00:00
5,0013-MHZWF,durga,None,Delhi,Women,1988-12-10 00:00:00
6,0013-SMEOE,mina,India,Meghalaya,Female,1976-09-21 00:00:00
7,0014-BMAQU,madan,India,Rajasthan,Male,1999-03-14 00:00:00
8,0015-UOCOJ,maya,None,Kathmandu,Women,1985-07-07 00:00:00
9,0016-QLJIS,arjun,Nepal,Kathmandu,Male,1993-10-29 00:00:00
10,0017-DINOC,shiva,India,Maharashtra,Men,1997-01-22 00:00:00
11,0017-IUDMW,rangadevi,India,Karnataka,Female,1981-06-18 00:00:00
12,0018-NYROU,chitra,None,Telangana,Female,2004-12-01 00:00:00
13,0019-EFAEP,raju,India,Meghalaya,Female,1992-04-25 00:00:00
14,0019-GFNTW,Madhav,India,Uttar Pradesh,Men,1979-11-11 00:00:00
15,0020-INWCK,parvati,India,Delhi,Female,1986-02-28 00:00:00
16,0020-JDNXP,rikim,India,Meghalaya,Female,1994-08-19 00:00:00
17,0021-IKXGC,vishakha,India,Rajasthan,Female,2000-09-02 00:00:00
18,0022-TCJCI,raghvendra,India,Telangana,Male,1983-12-30 00:00:00
19,0023-HGHWL,rishabh,India,Uttar Pradesh,Men,1991-05-14 00:00:00
20,0023-UYUPN,sudevi,India,Maharashtra,Women,1977-10-06 00:00:00

In [37]:
df_db_customer['dob']=pd.to_datetime(df_db_customer['dob'])

In [41]:
df_db_customer['gender'].unique()

array(['Male', 'Female', 'Women', 'Men'], dtype=object)

In [44]:
df_db_customer['gender']=df_db_customer['gender'].replace({'Men':'Male','Women':'Female'})
df_db_customer

    customerid customer_name country          state  gender        dob
0   0002-ORFBO        keshav   India    Maharashtra    Male 1982-04-12
1   0003-MKNFE        raghav   India      Karnataka    Male 1995-11-23
2   0004-TLHLJ        lalita   India          Delhi  Female 1978-02-15
3   0011-IGKFF         mohan   India       Nagaland    Male 2001-08-30
4   0013-EXCHZ          mira   India          Delhi  Female 1990-05-05
5   0013-MHZWF         durga    None          Delhi  Female 1988-12-10
6   0013-SMEOE          mina   India      Meghalaya  Female 1976-09-21
7   0014-BMAQU         madan   India      Rajasthan    Male 1999-03-14
8   0015-UOCOJ          maya    None      Kathmandu  Female 1985-07-07
9   0016-QLJIS         arjun   Nepal      Kathmandu    Male 1993-10-29
10  0017-DINOC         shiva   India    Maharashtra    Male 1997-01-22
11  0017-IUDMW     rangadevi   India      Karnataka  Female 1981-06-18
12  0018-NYROU        chitra    None      Telangana  Female 2004-12-01
13  0019-EFAEP          raju   India      Meghalaya  Female 1992-04-25
14  0019-GFNTW        Madhav   India  Uttar Pradesh    Male 1979-11-11
15  0020-INWCK       parvati   India          Delhi  Female 1986-02-28
16  0020-JDNXP         rikim   India      Meghalaya  Female 1994-08-19
17  0021-IKXGC      vishakha   India      Rajasthan  Female 2000-09-02
18  0022-TCJCI    raghvendra   India      Telangana    Male 1983-12-30
19  0023-HGHWL       rishabh   India  Uttar Pradesh    Male 1991-05-14
20  0023-UYUPN        sudevi   India    Maharashtra  Female 1977-10-06

In [45]:
df_db_customer['country'].unique()

array(['India', None, 'Nepal'], dtype=object)

In [48]:
df_db_customer[df_db_customer['country'].isna()]

    customerid customer_name country      state  gender        dob
5   0013-MHZWF         durga    None      Delhi  Female 1988-12-10
8   0015-UOCOJ          maya    None  Kathmandu  Female 1985-07-07
12  0018-NYROU        chitra    None  Telangana  Female 2004-12-01

In [53]:
state_country_mapping=df_db_customer.dropna(subset=['country']).set_index('state')['country'].to_dict()

df_db_customer['country']=df_db_customer['country'].fillna(df_db_customer['state'].map(state_country_mapping))
df_db_customer

    customerid customer_name country          state  gender        dob
0   0002-ORFBO        keshav   India    Maharashtra    Male 1982-04-12
1   0003-MKNFE        raghav   India      Karnataka    Male 1995-11-23
2   0004-TLHLJ        lalita   India          Delhi  Female 1978-02-15
3   0011-IGKFF         mohan   India       Nagaland    Male 2001-08-30
4   0013-EXCHZ          mira   India          Delhi  Female 1990-05-05
5   0013-MHZWF         durga   India          Delhi  Female 1988-12-10
6   0013-SMEOE          mina   India      Meghalaya  Female 1976-09-21
7   0014-BMAQU         madan   India      Rajasthan    Male 1999-03-14
8   0015-UOCOJ          maya   Nepal      Kathmandu  Female 1985-07-07
9   0016-QLJIS         arjun   Nepal      Kathmandu    Male 1993-10-29
10  0017-DINOC         shiva   India    Maharashtra    Male 1997-01-22
11  0017-IUDMW     rangadevi   India      Karnataka  Female 1981-06-18
12  0018-NYROU        chitra   India      Telangana  Female 2004-12-01
13  0019-EFAEP          raju   India      Meghalaya  Female 1992-04-25
14  0019-GFNTW        Madhav   India  Uttar Pradesh    Male 1979-11-11
15  0020-INWCK       parvati   India          Delhi  Female 1986-02-28
16  0020-JDNXP         rikim   India      Meghalaya  Female 1994-08-19
17  0021-IKXGC      vishakha   India      Rajasthan  Female 2000-09-02
18  0022-TCJCI    raghvendra   India      Telangana    Male 1983-12-30
19  0023-HGHWL       rishabh   India  Uttar Pradesh    Male 1991-05-14
20  0023-UYUPN        sudevi   India    Maharashtra  Female 1977-10-06

In [56]:
df_db_subscription.tail()

,customerid,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason,monthly_charges,cltv,churn_score
16,0020-JDNXP,2022-01-19,Organic,2024-01-19,Premium,Annual,None,None,20.99,550,62
17,0021-IKXGC,2021-07-07,Paid,2025-07-07,Standard,Annual,None,None,13.99,840,27
18,0022-TCJCI,2023-09-14,Refferal,2024-09-14,Basic,Monthly,2024-09-14,Forgot to cancel trial,16.99,42,99
19,0023-HGHWL,2020-06-23,Organic,2025-06-23,Premium,Annual,None,None,22.99,1955,7
20,0023-UYUPN,2022-12-31,Paid,2025-12-31,Standard,Monthly,None,None,13.99,790,47

In [55]:
df_db_subscription.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customerid               21 non-null     object
 1   subscription_start_date  21 non-null     object
 2   subscription_type        21 non-null     object
 3   renewal_date             21 non-null     object
 4   plan_type                21 non-null     object
 5   contract_type            21 non-null     object
 6   cancellation_date        6 non-null      object
 7   cancellation_reason      6 non-null      object
 8   monthly_charges          21 non-null     float64
 9   cltv                     21 non-null     int64
 10  churn_score              21 non-null     int64
dtypes: float64(1), int64(2), object(8)
memory usage: 1.9+ KB

In [58]:
date_col = ['subscription_start_date','renewal_date','cancellation_date']

df_db_subscription[date_col] = df_db_subscription[date_col].apply(pd.to_datetime)
df_db_subscription.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customerid               21 non-null     object
 1   subscription_start_date  21 non-null     datetime64[ns]
 2   subscription_type        21 non-null     object
 3   renewal_date             21 non-null     datetime64[ns]
 4   plan_type                21 non-null     object
 5   contract_type            21 non-null     object
 6   cancellation_date        6 non-null      datetime64[ns]
 7   cancellation_reason      6 non-null      object
 8   monthly_charges          21 non-null     float64
 9   cltv                     21 non-null     int64
 10  churn_score              21 non-null     int64
dtypes: datetime64[ns](3), float64(1), int64(2), object(5)
memory usage: 1.9+ KB

In [59]:
df_db_support.head()

,customerid,complaint_date,escalations,csat_score,col_1,comment
0,0003-MKNFE,2024-08-28 00:00:00,N,60,None,service issue
1,0003-MKNFE,2024-08-28 00:00:00,Y,10,None,demaned refund
2,0013-EXCHZ,2024-01-20 00:00:00,Y,20,None,None
3,0013-MHZWF,2025-03-18 00:00:00,N,90,None,guidance to renew
4,0013-SMEOE,2024-11-01 00:00:00,N,30,None,None

In [60]:
df_db_support.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customerid      9 non-null      object
 1   complaint_date  9 non-null      object
 2   escalations     9 non-null      object
 3   csat_score      9 non-null      int64
 4   col_1           0 non-null      object
 5   comment         4 non-null      object
dtypes: int64(1), object(5)
memory usage: 564.0+ bytes

In [61]:
df_db_support.drop(columns=['col_1','comment'],inplace=True)

In [62]:
df_db_support['complaint_date']=pd.to_datetime(df_db_support['complaint_date'])

In [63]:
df_db_support

   customerid complaint_date escalations  csat_score
0  0003-MKNFE     2024-08-28           N          60
1  0003-MKNFE     2024-08-28           Y          10
2  0013-EXCHZ     2024-01-20           Y          20
3  0013-MHZWF     2025-03-18           N          90
4  0013-SMEOE     2024-11-01           N          30
5  0017-IUDMW     2024-04-10           Y          25
6  0019-EFAEP     2024-09-27           Y          30
7  0022-TCJCI     2024-09-13           Y          10
8  0022-TCJCI     2024-09-14           N          90

In [64]:
#3. Feature Engineering and Data Analysis